name: Trigger Render Deployment
on:
  push:
    branches:
      - main
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          NODE_OPTIONS: --experimental-vm-modules
        run: npm test

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false #optional, default true
